flowchart TD
    %% Nodes for fighter
        SettingTarget("파이터 목표 설정")
        SettingTarget--> AreWeInDanger("보물을 가지고 있는가?")
        
        AreWeInDanger--      "Yes"   --> TargetExit("목표 = 출구")
        AreWeInDanger--      "No"    --> AmIInDanger("내 체력이 30% 이하인가?")
        
        AmIInDanger--      "Yes"   --> IsClericAlive("클레릭이 살아 있는가?")
        AmIInDanger--      "No"    --> TargetDragon("목표 = 드래곤")
        
        IsClericAlive--      "Yes"   --> TargetCleric("목표 = 클레릭")
        IsClericAlive--      "No"    --> TargetDragon("목표 = 드래곤")
        
        
        TargetCleric--> MoveStart("행동 시작")
        TargetDragon--> MoveStart("행동 시작")
        TargetExit--> MoveStart("행동 시작")

        MoveStart--> AmIOnTarget("목표에 도달했나?")

        AmIOnTarget--      "Yes"   --> CanIAttack("행동력이 1 이상이며 <br>드래곤이 내 공격 범위 안에 있나?")
        AmIOnTarget--      "No"    --> CanIMove("이동력이 1 이상인가?")

        CanIMove--      "Yes"   --> MoveToTarget("목표로 1칸 이동")
        CanIMove--      "No"    --> TurnEnd("턴 종료")
        MoveToTarget--> DecreaseMovePoint("이동력을 1 소모")

        CanIAttack--      "Yes"   --> IsClericAlive2("클레릭이 살아 있는가?")
        CanIAttack--      "No"    --> CanIMove("이동력이 1 이상인가?")
        IsClericAlive2--      "Yes"   --> DoIHaveBuffAndDoesDragonHasDebuff("내가 버프를 받고,<br>드래곤이 디버프를 받고있는가?")
        DoIHaveBuffAndDoesDragonHasDebuff--      "Yes"   --> DoIHaveSpellSlot("주문 슬롯이 1개 이상인가?")
        DoIHaveBuffAndDoesDragonHasDebuff--      "No"    --> AttackDragon("드래곤에게 일반 공격사용")
        IsClericAlive2--      "No"    --> DoIHaveSpellSlot("주문 슬롯이 1개 이상인가?")
        DoIHaveSpellSlot--      "Yes"   --> SpellAttackDragon("드래곤에게<br>주문 슬롯을 사용하는<br>가장 강력한 공격 사용")
        DoIHaveSpellSlot--      "No"    --> AttackDragon("드래곤에게 일반 공격사용")

        AttackDragon--      "Yes"   --> DecreaseActionPoint("행동력을 1 소모")

        SpellAttackDragon--      "Yes"   --> DecreaseSpellSlot("주문 슬롯을 소모")
        DecreaseSpellSlot--      "Yes"   --> DecreaseActionPoint("행동력을 1 소모")

        DecreaseMovePoint--      "Yes"   --> CanIAttack("행동력이 1 이상이며 <br>드래곤이 내 공격 범위 안에 있나?")
        
        DecreaseActionPoint--      "Yes"   --> AmIOnTarget("목표에 도달했나?")
    %% You can add notes with two "%" signs in a row!